# GitHub Releases
github_releases:
  - name: Obtainium
    repo: ImranR98/Obtainium
    pattern: app-arm64-v8a-release.apk

  - name: Unciv
    repo: yairm210/Unciv
    pattern: Unciv-signed.apk

# Direct Download URLs
direct_downloads:
  - name: RetroArch
    url: https://buildbot.libretro.com/stable/1.21.0/android/RetroArch_aarch64.apk

# Scrape from Websites
web_scraping:
  - name: Dolphin
    page_url: https://dolphin-emu.org/download/
    link_pattern: https://dl\.dolphin-emu\.org/builds/.+dolphin-master-\d+-\d+\.apk